Add test for nodeConnector output cache
zsoltk/RIBs pull request #8
Opened 2021-05-11 09:00 UTC by SamuPS

2021-05-13 09:59 UTC, CherryPerry requested changes

2021-05-13 09:59 UTC, CherryPerry commented on libraries/rib-base-test/src/main/java/com/badoo/ribs/test/BaseConnectableNodeTest.kt
> +abstract class BaseConnectableNodeTest {
You leak unnecessary utility class to library consumers.
I think it is easier to duplicate test methods rather than implement separate utility Gradle module for it.

2021-05-13 09:59 UTC, CherryPerry commented on libraries/rib-base-test/build.gradle
> +    implementation deps.test.mockitoKotlin
See comment below and remove.

2021-05-13 09:59 UTC, CherryPerry commented on libraries/rib-base-test/src/main/java/com/badoo/ribs/test/BaseConnectableNodeTest.kt
> +    abstract fun WHEN_child_emit_some_output_before_it_is_attached_to_parent_THEN_parent_receive_the_output_after_child_attach_finished()
You can use Kotlin names here fun `WHEN child emit...`()

2021-05-13 09:59 UTC, CherryPerry commented on libraries/rib-base-test/src/main/java/com/badoo/ribs/test/helper/connectable/ConnectableTestNode.kt
> +class ConnectableTestNode(
Same here.
rib-base-test it not an internal utility module, but publicity available one that is intended to be used.

2021-05-13 09:59 UTC, CherryPerry commented on libraries/rib-base/src/test/java/com/badoo/ribs/clienthelper/connector/NodeConnectorTest.kt
> +                    barrier.await()
Specify timeout for every `await` you use to avoid dead locks (locally and on CI). Like extension function with 1 minute default timeout.

2021-05-13 09:59 UTC, CherryPerry commented on libraries/rib-base/src/test/java/com/badoo/ribs/clienthelper/connector/NodeConnectorTest.kt
> +        firstTestObserver.assertValueAt(0, Output1)
`firstTestObserver.assertValues(Output1, Output2, Output3)`
> Assert that the TestObserver/TestSubscriber received only the specified values in the specified order.

2021-05-13 09:59 UTC, CherryPerry commented on libraries/rib-base/src/test/java/com/badoo/ribs/clienthelper/connector/NodeConnectorTest.kt
> +        nodeConnector.output.observe { firstTestObserver.onNext(it) }
`nodeConnector.output.observe(firstTestObserver)`

2021-05-13 09:59 UTC, CherryPerry commented on libraries/rib-rx2/src/test/java/com/badoo/ribs/rx2/clienthelper/conector/helpers/Rx2ConnectableTestNode.kt
> +    router: Router<*> = mock(),
Try to run without router.

2021-05-13 10:23 UTC, zsoltk commented on libraries/rib-base-test/src/main/java/com/badoo/ribs/test/BaseConnectableNodeTest.kt
> +abstract class BaseConnectableNodeTest {
This was my suggestion, the point being not just to avoid copy-paste, but to actually enforce same expectations (test suite) for all implementations.

2021-05-13 13:03 UTC, SamuPS commented on libraries/rib-base-test/src/main/java/com/badoo/ribs/test/BaseConnectableNodeTest.kt
> +abstract class BaseConnectableNodeTest {
Do you have any suggestions about how to use the abstraction approach without exposing it? If the base-test is not supossed to be exposed, i would go for removing the abstract or to create an internal utils module, but not sure how desirable is that.

2021-05-13 13:03 UTC, SamuPS commented on libraries/rib-base-test/src/main/java/com/badoo/ribs/test/helper/connectable/ConnectableTestNode.kt
> +class ConnectableTestNode(
I will move it away, it was added here to avoid some interface naming conflict. But if this is the case, let's rename the interface instead

2021-05-13 13:03 UTC, SamuPS commented on libraries/rib-base/src/test/java/com/badoo/ribs/clienthelper/connector/NodeConnectorTest.kt
> +        nodeConnector.output.observe { firstTestObserver.onNext(it) }
Not possible for this ones, but i would do it for the Rx2 ones.

2021-05-13 13:03 UTC, SamuPS commented on libraries/rib-rx2/src/test/java/com/badoo/ribs/rx2/clienthelper/conector/helpers/Rx2ConnectableTestNode.kt
> +    router: Router<*> = mock(),
Removed, i also removed other non required elements.

2021-05-13 13:18 UTC, CherryPerry commented on libraries/rib-base/src/main/java/com/badoo/ribs/core/plugin/Plugin.kt
> +    fun onNodeBuild() {}
Why did you rename it?

2021-05-13 14:53 UTC, SamuPS commented on libraries/rib-base/src/main/java/com/badoo/ribs/core/plugin/Plugin.kt
> +    fun onNodeBuild() {}
Otherwise no class extending Node defined inside rib-base can extend connectables, as there is an interfaces clash(Node onBuild is internal).

2021-05-13 14:55 UTC, SamuPS commented on libraries/rib-base/src/main/java/com/badoo/ribs/core/plugin/Plugin.kt
> +    fun onNodeBuild() {}
Basically this has to do with taking away ConnectableTestNode back to rib-base. Maybe we do need a new module for internal test utility.

2021-05-13 15:08 UTC, CherryPerry commented on libraries/rib-base/src/main/java/com/badoo/ribs/core/plugin/Plugin.kt
> +    fun onNodeBuild() {}
Renaming internal method seems like more easy way, it will affect only one file.

I start thinking, that it was a bad idea to let Node implement Plugins (because of name clash for example). Simple check inside `node.onAttach()` like `if (this is Connectable) this.unlock()` maybe was not that bad.

2021-05-14 08:23 UTC, SamuPS commented on libraries/rib-base/src/main/java/com/badoo/ribs/core/plugin/Plugin.kt
> +    fun onNodeBuild() {}
Well, the scenario for this clash shouldn't be a concern for the library users isn't it? I find pretty flexible the idea of Node implementing the plugings, but also my understanding it not as deep as your so, open to go this way.

2021-05-14 10:09 UTC, zsoltk commented on libraries/rib-base-test/src/main/java/com/badoo/ribs/test/BaseConnectableNodeTest.kt
> +abstract class BaseConnectableNodeTest {
I don't think it's a problem to expose it. We also can't provide all possible implementations of `Connectable`, so it might even help to have this test suite definition openly available.

2021-05-14 10:16 UTC, zsoltk commented on libraries/rib-base/src/main/java/com/badoo/ribs/core/plugin/Plugin.kt
> +    fun onNodeBuild() {}
Let's keep plugin method name the same and change the internal method.

2021-05-18 18:07 UTC, merged